version: '3'

services:
  searxng:
    image: searxng/searxng
    container_name: rightclaick_searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng-config/settings.yml:/etc/searxng/settings.yml
    environment:
      - INSTANCE_NAME=rightclaick_search
      - BASE_URL=http://localhost:8080/
      - ULTRASECRET=${SEARXNG_SECRET:-"ultrasecretkey"}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped 